### PR TITLE
Allow 'configure' to import yaml settings nested deeper than 2 levels

### PR DESCRIPTION
**Pull request by danwelch3**
Resolves meshtastic/python#466

### CODE REVIEW

**Comment by thebentern** [comment]
Please sign the CLA

**Comment by danwelch3** [comment]
I've signed it a few times. I did it first before submitting the PR, and
again after when I saw the warning. Is there any way other than the link in
the warning?

**Comment by AeroXuk** [comment]
@danwelch3
Please sign the CLA so that this change can be merged.
I've added a few extra edits under pull request #543 however these also can't be merged until you've signed the CLA.
You can sign it by clicked the below and agreeing the T&C.

https://cla-assistant.io/meshtastic/python?pullRequest=470

**Comment by danwelch3** [comment]
I've signed the CLA.  In the past I had issues with it showing, so let me know if it worked this time.

**Comment by AeroXuk** [comment]
@danwelch3 You may need to double check that the email address you used on the git commit is linked the the same account you signed the CLA with.  I can see the email on the commit is linked to this account @dwsc, but the PR is raised with @danwelch3.

**Comment by danwelch3** [comment]
Thanks for pointing that out.  I signed the CLA with the other account now.

**Pull request merged**
