### PR TITLE
Adding mypy typing

### PR DESCRIPTION
**Pull request by william-stearns**
Initial attempt to add python type hints to the majority of the (non pb2) python files in this repo.  There are a few notes about things that may need attention, but it's largely focused on type hints.

### CODE REVIEW

**Comment by william-stearns** [comment]
I don't know how you'd like to see PRs generated.  Please let me know if I need to do anything in another way to fit with your workflow.

**Comment by holdenweb** [comment]
It appears the only thing that is currently holding up the PR (besides a committer with time to review it) is the non-existence of the `BLEClient` entity reference in ble_interface.py, line 121.

The annotation says you are trying to return an object of a non-existent class - just click on the "Details" links under "Some checks were not successful".

**Comment by william-stearns** [comment]
Thank you so much, @holdenweb !  I hadn't realized the ball was back in my court.
I've removed the references to BLEClient typing, with the hope this is enough to get it going.

**Comment by william-stearns** [comment]
I just went through github's "resolve conflicts".  It appears this is ready again to be reviewed.  Please let me know if something else is needed.

**Comment by ianmcorvidae** [comment]
I'm sorry to have let this languish so long, completely lost track of it. I'm running the CI again which might pull up some issues, but other than those/fixing anything they uncover, this looks good. Thanks for the PR and your patience both!

If I lose track of it again, feel free to tag me in a comment to send another email, or ping me on discord if you're there (I'm mian, username m_ia_n, there).

**Comment by william-stearns** [comment]
See #681 for a replacement for this PR that fixes the above CI errors.

**Comment by ianmcorvidae** [comment]
That works, though pushing it to this same branch would also have been fine. I'll close this PR for now in favor of the other one though.

**Pull request closed without merging**
