### PR TITLE
Adds support for ble logging characteristic

### LINKED ISSUE #609: Add support for meshtastic logging over BLE
... to the existing meshtastic python BLE code.

Crib from https://github.com/meshtastic/Meshtastic-Apple/blob/9fb849affba15d0ca8f55e4c657d0063bc1d771e/Meshtastic/Helpers/BLEManager.swift
per @garthvh

### PR DESCRIPTION
**Pull request by thebentern**
Closes #609 
image

### CODE REVIEW

**Comment by geeksville** [comment]
ooh this is super useful!

**Comment by geeksville** [comment]
btw - @thebentern no need for you to try and fix the build errors which were reported.  (by coincidence)  When I recently tried using --ble it seems to me that the  old version of the "Bleak" BLE library that were using had problems now connecting to meshtastic devices.  But the new/current version has a number of breaking API changes.  My WIP branch to make the current Bleak work for us is here:

https://github.com/geeksville/Meshtastic-python/tree/pr-fixbluetooth

I'll finish that work up and send a PR in.  Or if it is okay with you I can merge it into this PR?

**Comment by thebentern** [comment]
Sure!

**Comment by geeksville** [comment]
@thebentern okay - fixes to make bleak work robustly again on Linux are in.  Would you mind trying on OS-X to confirm I didn't break anything there?

**Comment by geeksville** [comment]
oops - I forgot to run pylint before submitting.  fixing.

**Comment by geeksville** [comment]
btw: note: I added an optional  --ble-dest <addr> flag to specify target device.  --ble now takes no args and if no device is specified and we can only find one paired meshtastic device, we just use that.

**Comment by thebentern** [comment]
@geeksville I'm having some environment issues on my OS-X machine right now but it tested out fine on my Windows box, so I say ship it!

**Comment by geeksville** [comment]
heh - I'm not sure how to fix the sentry thing.  Because I kinda doubt that sentry had any real code coverage testing on the existing (buggier) BLE code ;-)

**Review by geeksville — APPROVED** [review]
LGTM

**Comment by ianmcorvidae** [comment]
Nice, looks good to me!

**Pull request merged**
