### PR TITLE
Bugfix 466 yaml import

### PR DESCRIPTION
**Pull request by AeroXuk**
Allow 'configure' to import yaml settings nested deeper than 2 levels.
Expands apon #470, #466

### CODE REVIEW

**Comment by ianmcorvidae** [comment]
Sorry I haven't had a chance to dig into this (and @dwsc / @danwelch3 's prior change in #470 ). I see you fixed the merge conflicts that are in that PR; I set off a CI run so we can see if there's any lint/test/type things to fix up here, and I'll hopefully be able to review it sometime soon as well.

**Comment by ianmcorvidae** [comment]
Looks like there's a minor merge conflict with #544 that was just merged, and pylint would like `traverseConfig` to have a docstring. However aside from that this looks good to me. If you get those issues resolved I can merge outright, otherwise I'll try to sit down and get those bits handled soon in order to merge.

Sorry about taking so long to get to reviewing this, and thank you for the pull request!

**Comment by danwelch3** [comment]
Thanks for reviewing.  I updated #470 to include the docstring on traverseConfig.

**Comment by ianmcorvidae** [comment]
Cool. I got the merge conflict part handled, and I'll check to make sure CI is still happy. Thanks again to both of you for the fixes!

**Pull request merged**
