### PR TITLE
BLE Support

### PR DESCRIPTION
**Pull request by wnagele**
Started a refactor of the current WIP BLE support with SimplePyBLE as it supports more platforms out of the box. This is not ready for merge but I would like to invite feedback.

### CODE REVIEW

**Comment by wnagele** [comment]
One thing I couldn't get to work thus far is the subcription to `FROMNUM_UUID`. Somehow this never seems to be called. Any help with that much appreciated.

**Comment by garthvh** [comment]
Gets called every time there are updates.

**Comment by wnagele** [comment]
> Gets called every time there are updates.
That's what I expected but didn't see happening. I'll try to dig further on this.

**Comment by wnagele** [comment]
Turns out the issue on the notifies was in the SimpleBLE library. Have switched it out for Bleak which is used more widely (unfortunately async only which makes the code a bit clunky).

**Comment by wnagele** [comment]
This should be in a state for `beta` testing now. I can only test this on _MacOS_ right now. So am looking for folks to especially test on _Windows_ and _Linux_ too.

You can use `--ble-scan` to perform a scan for Meshtastic devices and then `--ble <address|name>` to connect to this device (similar to how you would use `--host` for a TCP based connection).

Please respond here if you tested this, which platform it was on and if issues were encountered provide output of run with addeed`--debug` flag. 🙇

**Comment by wnagele** [comment]
Beta testing:
- [ ] MacOS
- [ ] Linux
- [ ] Windows

**Comment by lukipuki** [comment]
Hi, tested on Linux, there's an access to `None`. I can help debugging this - I'm planning on writing BLE support in Rust but the python CLI client is also of interest to me.

Here's the debug log.

```DEBUG file:__main__.py common line:935 Not logging serial output
DEBUG file:ble_interface.py __init__ line:36 Threads starting
DEBUG file:selector_events.py __init__ line:54 Using selector: EpollSelector
DEBUG file:ble_interface.py __init__ line:48 Threads running
DEBUG file:ble_interface.py __init__ line:55 BLE connecting to: D6:23:D5:30:45:29
DEBUG file:manager.py async_init line:323 initial properties: {'/org/bluez': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.AgentManager1': {}, 'org.bluez.ProfileManager1': {}}, '/org/bluez/hci0': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.Adapter1': {'Address': 'B0:A4:60:C0:4C:DD', 'AddressType': 'public', 'Name': 'BlueZ 5.70', 'Alias': 'LukasJeSuper', 'Class': 8126732, 'Powered': True, 'PowerState': 'on', 'Discoverable': False, 'DiscoverableTimeout': 180, 'Pairable': True, 'PairableTimeout': 0, 'Discovering': False, 'UUIDs': ['00001133-0000-1000-8000-00805f9b34fb', '0000110e-0000-1000-8000-00805f9b34fb', '00001105-0000-1000-8000-00805f9b34fb', '00001132-0000-1000-8000-00805f9b34fb', '00001200-0000-1000-8000-00805f9b34fb', '00001104-0000-1000-8000-00805f9b34fb', '0000110c-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000112f-0000-1000-8000-00805f9b34fb', '0000180a-0000-1000-8000-00805f9b34fb', '0000110b-0000-1000-8000-00805f9b34fb', '00001800-0000-1000-8000-00805f9b34fb', '0000111f-0000-1000-8000-00805f9b34fb', '0000110a-0000-1000-8000-00805f9b34fb', '00001106-0000-1000-8000-00805f9b34fb', '0000111e-0000-1000-8000-00805f9b34fb'], 'Modalias': 'usb:v1D6Bp0246d0546', 'Roles': ['central', 'peripheral']}, 'org.freedesktop.DBus.Properties': {}, 'org.bluez.GattManager1': {}, 'org.bluez.Media1': {'SupportedUUIDs': ['0000110a-0000-1000-8000-00805f9b34fb', '0000110b-0000-1000-8000-00805f9b34fb']}, 'org.bluez.NetworkServer1': {}, 'org.bluez.LEAdvertisingManager1': {'ActiveInstances': 0, 'SupportedInstances': 12, 'SupportedIncludes': ['tx-power', 'appearance', 'local-name'], 'SupportedSecondaryChannels': ['1M', '2M', 'Coded']}}, '/org/bluez/hci0/dev_D6_23_D5_30_45_29': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.Device1': {'Address': 'D6:23:D5:30:45:29', 'AddressType': 'random', 'Name': 'MB_4529', 'Alias': 'MB_4529', 'Paired': True, 'Bonded': True, 'Trusted': True, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['00001530-1212-efde-1523-785feabcd123', '00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000180a-0000-1000-8000-00805f9b34fb', '0000180f-0000-1000-8000-00805f9b34fb', '6ba1b218-15a8-461f-9fa8-5dcae273eafd'], 'Adapter': '/org/bluez/hci0', 'ServicesResolved': False}, 'org.freedesktop.DBus.Properties': {}}, '/org/bluez/hci0/dev_D4_D4_DA_82_D8_B6': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.Device1': {'Address': 'D4:D4:DA:82:D8:B6', 'AddressType': 'public', 'Name': 'SI-Radio-Bridge', 'Alias': 'SI-Radio-Bridge', 'Class': 180496, 'Icon': 'computer', 'Paired': True, 'Bonded': True, 'Trusted': True, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['00001101-0000-1000-8000-00805f9b34fb'], 'Adapter': '/org/bluez/hci0', 'ServicesResolved': False}, 'org.freedesktop.DBus.Properties': {}}, '/org/bluez/hci0/dev_AC_3E_B1_1B_E7_06': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.Device1': {'Address': 'AC:3E:B1:1B:E7:06', 'AddressType': 'public', 'Name': 'Pixel 6a', 'Alias': 'Pixel 6a', 'Class': 5898764, 'Icon': 'phone', 'Paired': True, 'Bonded': True, 'Trusted': True, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['00001105-0000-1000-8000-00805f9b34fb', '0000110a-0000-1000-8000-00805f9b34fb', '0000110c-0000-1000-8000-00805f9b34fb', '0000110d-0000-1000-8000-00805f9b34fb', '0000110e-0000-1000-8000-00805f9b34fb', '00001112-0000-1000-8000-00805f9b34fb', '00001115-0000-1000-8000-00805f9b34fb', '00001116-0000-1000-8000-00805f9b34fb', '0000111f-0000-1000-8000-00805f9b34fb', '0000112d-0000-1000-8000-00805f9b34fb', '0000112f-0000-1000-8000-00805f9b34fb', '00001132-0000-1000-8000-00805f9b34fb', '00001200-0000-1000-8000-00805f9b34fb', '00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', 'a82efa21-ae5c-3dde-9bbc-f16da7b16c5a'], 'Modalias': 'bluetooth:v00E0p1200d1436', 'Adapter': '/org/bluez/hci0', 'ServicesResolved': False}, 'org.freedesktop.DBus.Properties': {}, 'org.bluez.Network1': {'Connected': False}, 'org.bluez.MediaControl1': {'Connected': False}}, '/org/bluez/hci0/dev_E3_44_4E_18_F7_A4': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.Device1': {'Address': 'E3:44:4E:18:F7:A4', 'AddressType': 'random', 'Name': 'LPR_f7a4', 'Alias': 'LPR_f7a4', 'Paired': True, 'Bonded': True, 'Trusted': True, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['00001530-1212-efde-1523-785feabcd123', '00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '0000180a-0000-1000-8000-00805f9b34fb', '0000180f-0000-1000-8000-00805f9b34fb', '6ba1b218-15a8-461f-9fa8-5dcae273eafd'], 'Adapter': '/org/bluez/hci0', 'ServicesResolved': False}, 'org.freedesktop.DBus.Properties': {}}, '/org/bluez/hci0/dev_A3_3E_AA_A0_DC_A2': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.Device1': {'Address': 'A3:3E:AA:A0:DC:A2', 'AddressType': 'public', 'Name': 'OontZ Angle 3 Plus', 'Alias': 'OontZ Angle 3 Plus', 'Class': 2360328, 'Icon': 'audio-headset', 'Paired': True, 'Bonded': True, 'Trusted': True, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['0000110b-0000-1000-8000-00805f9b34fb', '0000110c-0000-1000-8000-00805f9b34fb', '0000110d-0000-1000-8000-00805f9b34fb', '0000110e-0000-1000-8000-00805f9b34fb', '0000111e-0000-1000-8000-00805f9b34fb'], 'Adapter': '/org/bluez/hci0', 'ServicesResolved': False}, 'org.freedesktop.DBus.Properties': {}, 'org.bluez.MediaControl1': {'Connected': False}}}
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0): ['org.bluez.Adapter1', {'Discovering': <dbus_fast.signature.Variant ('b', True)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -75)>, 'TxPower': <dbus_fast.signature.Variant ('n', 0)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -74)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -74)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -74)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -74)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -75)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -74)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -79)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -74)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -74)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -74)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -79)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -74)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -74)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -74)>}, []]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_D6_23_D5_30_45_29): ['org.bluez.Device1', {}, ['TxPower', 'RSSI']]
DEBUG file:manager.py _parse_msg line:860 received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0): ['org.bluez.Adapter1', {'Discovering': <dbus_fast.signature.Variant ('b', False)>}, []]
Traceback (most recent call last):
  File "/home/lukas/Cpp/sokol/yaroc/.venv/bin/meshtastic", line 33, in <module>
    sys.exit(load_entry_point('meshtastic', 'console_scripts', 'meshtastic')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/repos/meshtastic-python/meshtastic/__main__.py", line 1366, in main
    common()
  File "/home/lukas/repos/meshtastic-python/meshtastic/__main__.py", line 956, in common
    client = BLEInterface(args.ble, debugOut=logfile, noProto=args.noproto)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/repos/meshtastic-python/meshtastic/ble_interface.py", line 56, in __init__
    self.client = self.await_bleak(self.connect(address))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/repos/meshtastic-python/meshtastic/ble_interface.py", line 173, in await_bleak
    return self.run_bleak(coro).result(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/lukas/repos/meshtastic-python/meshtastic/ble_interface.py", line 114, in connect
    await client.pair()
  File "/home/lukas/Cpp/sokol/yaroc/.venv/lib/python3.11/site-packages/bleak/__init__.py", line 629, in pair
    return await self._backend.pair(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/Cpp/sokol/yaroc/.venv/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 435, in pair
    reply = await self._bus.call(
                  ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'call'
```

**Comment by wnagele** [comment]
I think that I had the order wrong and since MacOS does not require pairing it didn't matter on my end. Have now switched to perform `connect` before `pair`. You mind re-testing?

**Comment by lukipuki** [comment]
Now it connects to the device but then hangs without any response. I waited about 3 minutes and then pressed Ctrl-C twice to interrupt. You can see it at the end of the log as the `KeyboardInterrupt` exception. Attached log:
[ble.log](https://github.com/meshtastic/python/files/13932493/ble.log)

Interestingly, I encountered the same behavior when I did the same thing in Rust (using `btleplug` library), there was no response from the device. I suspect something is wrong with BLE on my laptop, I can try another computer or a different OS (Windows or another Linux). Although I'm not sure how probable it is.

**Comment by wnagele** [comment]
Does `--ble-scan` work for you? If you connect to your device using TCP or Serial - does that work?

**Comment by wnagele** [comment]
Oh and one other thing - make sure you don't have anything else still holding that connection open. If you for instance have it paired to your phone via BLE this connection will block the one here from proceeding.

**Comment by lukipuki** [comment]
Yes, `--ble-scan` works as well as connecting via serial.

And the device wasn't connected to any phone. You can see the line "BLE connected" in the attached log file. It got connected while running the CLI command but then it just hanged.

**Comment by wnagele** [comment]
I've added the explicit request for a response in those writes. Maybe the Linux backend gets this wrong - the logs don't reveal that detail unfortunately. Could you re-test?

**Comment by lukipuki** [comment]
I've tested it on Windows 10 and it works! Tested `--info`, `--nodes` and `--export-config`.

Regarding the Linux problem, I'm proficient in Python, I'll debug it locally and get back to you (it might take a few days). I think that's the most effective way to do it. As I said previously, I'm also suspicious of my Linux installation of bluez, as I have experienced the same hang without response using a Rust library on Linux.

**Comment by wnagele** [comment]
I think you didn't pair the BLE device using `bluetoothctl` before? I think that is the only way to perform the PIN pairing prior to using that device. I find the Bleak docs on this very lacking.

**Comment by lukipuki** [comment]
It works now!

The device was paired incorrectly. The GUI in my desktop environment doesn't ask for a PIN when pairing and then (incorrectly) claims that the device has been paired. I could somehow connect to it is well.

I used `bluetoothctl` to pair both devices I have, then I entered the PIN and the `--ble` command works.

And my Rust code works now, too.

However, there's definitely some bug somewhere in the bluetooth stack on my laptop, so I'll file a bug.

**Comment by wnagele** [comment]
Alright - @garthvh or @thebentern this should be good to merge now. Tested across major systems.

**Review by thebentern — APPROVED** [review]

**Pull request merged**
